# EXP_NAME: 'YOUR_EXPERIMENT_NAME'
RNG_SEED: 2026
DATASET:
  NAME: TINYIMAGENET 
  ROOT_DIR: './data/tiny-imagenet'
  VAL_RATIO: 0.05
  AUG_METHOD: 'hflip'
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 200
OPTIM:
  TYPE: 'adam'
  BASE_LR: 0.0005
  LR_POLICY: none
  LR_MULT: 0.1
  # STEPS: [0, 60, 120, 160, 200] 
  MAX_EPOCH: 150
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 100
  IM_SIZE: 64
  EVAL_PERIOD: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
ACTIVE_LEARNING:
  INIT_L_RATIO: 0.
  BUDGET_SIZE: 200
  MAX_ITER: 5